# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uts.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uts.ui'
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uts.ui'
# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        
        # Layout untuk input database
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 371, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        
        # Layout untuk input nama database untuk koneksi
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 90, 371, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_connect = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_connect.setObjectName("label_connect")
        self.horizontalLayout_3.addWidget(self.label_connect)
        self.lineEdit_connect = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_connect.setObjectName("lineEdit_connect")
        self.horizontalLayout_3.addWidget(self.lineEdit_connect)

        # Layout untuk tombol
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 230, 361, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_create = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_create.setObjectName("pushButton_create")
        self.horizontalLayout_2.addWidget(self.pushButton_create)
        self.pushButton_connect = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.horizontalLayout_2.addWidget(self.pushButton_connect)
        
        # Label untuk hasil
        self.labelResult = QtWidgets.QLabel(Form)
        self.labelResult.setGeometry(QtCore.QRect(20, 270, 361, 20))
        self.labelResult.setObjectName("labelResult")
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
        # Hubungkan tombol dengan fungsi
        self.pushButton_create.clicked.connect(self.create_database)
        self.pushButton_connect.clicked.connect(self.db_connect)

    def create_database(self):  
        try:  
            mydb = mc.connect(  
                host="localhost",  
                user="root",  
                password=""  
            )  
            cursor = mydb.cursor()  
            dbname = self.lineEdit.text()  
            
            # Cek apakah database sudah ada
            cursor.execute("SHOW DATABASES LIKE '{}'".format(dbname))
            if cursor.fetchone():
                self.labelResult.setText(f"Database '{dbname}' sudah ada.")
            else:
                cursor.execute(f"CREATE DATABASE {dbname}")
                self.labelResult.setText(f"Database '{dbname}' berhasil dibuat!")  
        except mc.Error as e:  
            self.labelResult.setText(f"Gagal membuat database: {str(e)}")

    def db_connect(self):  
        try:  
            dbname = self.lineEdit_connect.text()  # Ambil nama database dari input
            mydb = mc.connect(  
                host="localhost",  
                user="root",  
                password="",  
                database=dbname  # Menggunakan database yang dimasukkan
            )  
            self.labelResult.setText(f"Berhasil terhubung dengan database '{dbname}'.")  
        except mc.Error as err:  
            self.labelResult.setText(f"Gagal terhubung: {str(err)}")
    
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Database Manager"))
        self.label.setText(_translate("Form", "Nama Database untuk Buat"))
        self.label_connect.setText(_translate("Form", "Nama Database untuk Koneksi"))
        self.pushButton_create.setText(_translate("Form", "Buat Database"))
        self.pushButton_connect.setText(_translate("Form", "Cek Koneksi"))
        self.labelResult.setText(_translate("Form", "Status akan muncul di sini."))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

